name: Nordic e-infrastructure collaboration
highlighter: pygments

markdown_ext: wiki
markdown: pandoc
pandoc:
   format: html5
   extensions:
       from: mediawiki

defaults:
  -
    scope:
        path: ""
        type: "pages"
    values:
        layout: menu
        menu: 100
  -
    scope:
        path: ""
        type: "posts"
    values:
        layout: news
         
paginate: 5
paginate_path: "/news/page:num/"